<template>
  <div>
    <Nav />

    <div class="is-full">
      <img
        class="header"
        src="https://2021.igem.org/wiki/images/thumb/0/0b/T--USP-Brazil--IGEM-USP-Notebook-Bannernotebook.png/800px-T--USP-Brazil--IGEM-USP-Notebook-Bannernotebook.png"
      />
    </div>

    <section class="columns">
      <div class="column is-one-fifth"></div>
      <div class="content column is-three-fifth">
        <p>
          The plants (Micro-Tom) were transformed with the support of the
          <b>Plant Transformation Facility Pangeia Biotech</b> (São Paulo,
          Brazil)
          <a href="https://www.pangeiabiotech.com/"
            >(https://www.pangeiabiotech.com/).</a
          >
          The circuit LAT52_CYP6G1_GUS inserted on the plasmid was transferred
          to bacteria <i>Agrobacterium tumefaciens</i>, and then it was
          transfected in prepared undifferentiated plant cells. The positive
          transformants for resistance marker were grown on
          <b><i>kanamycin medium</i></b
          >, showing the success at the first step of transfection and insertion
          of plasmid by bacteria (Figure 1).
        </p>

        <h2>1 July 2021 - Transformation (Pangeia Biotech)</h2>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/5/54/T--USP-Brazil--IGEM-USP-Notebook-Microtom.png/514px-T--USP-Brazil--IGEM-USP-Notebook-Microtom.png"
            alt=""
          />
        </figure>

        <h2>
          July 28th 2021 - First plant growth on vessels (Pangeia Biotech)
        </h2>

        <p>
          When the plants reached 7 cm in size they were each transplanted into
          a pot and stayed in a greenhouse with a specific light radiation and
          temperature that promotes growth for ten days (Figure 2).
        </p>
        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/e/ea/T--USP-Brazil--IGEM-USP-Notebook-Transformants.png/578px-T--USP-Brazil--IGEM-USP-Notebook-Transformants.png"
            alt=""
          />
        </figure>

        <h2>
          August 3rd 2021 - Pollen and leaf extraction for control Micro-tom
          (Members: Caio K. and Luiz)
        </h2>

        <p>
          Our experiments were carried with <b>GOLDEN2-LIKE (GLK)</b> mutants
          Micro-tom. The gene is a transcriptional factor that regulates plastid
          and chlorophyll levels and generates phenotypes without an uneven
          green coloring on the fruits (Figure 3) [1]. For RNA/DNA extraction
          and cDNA synthesis the pollen and leaves were collected earlier from
          control (u/u mutants, without our circuit part) , while the samples
          from transformants plants were collected later, in September.
        </p>
        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/6/62/T--USP-Brazil--IGEM-USP-Notebook-Tomatofruits.png/800px-T--USP-Brazil--IGEM-USP-Notebook-Tomatofruits.png"
            alt=""
          />
        </figure>

        <p>
          The pollen was extracted with the support of an electric toothbrush
          without the bristles and inserted on a RNAse and DNase-free microtube.
          The vibration generated by the electric tooth brush causes the pollen
          to be expelled into the tubes (Video 1). We obtained a maximum of 20
          mg of pollen by plant from young flowers, while older flowers had a
          maximum of 2 mg approximately. After the pollen collection, we capped
          the tube and stored it inside liquid nitrogen at -80°C in laboratory.
        </p>
        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/e/e0/T--USP-Brazil--IGEM-USP-Notebook-gif.gif/600px-T--USP-Brazil--IGEM-USP-Notebook-gif.gif"
          />
        </figure>
        
        <small>
          Video 1. Extraction of Micro-tom pollen control by Dr. Bruno Silvestre
          Lira - Laboratório de Genética Molecular de Plantas (GMP,
          IB-USP).</small
        >

        <p>
          For the leafs, we cut them it with scissors and stored it on the same
          way of pollen. The average weight of each leaf was 20 mg.
        </p>

        <h2>
          August 6th 2021 - Validation of RNA extraction for control plants
          (Members: Caio K.)
        </h2>

        <p>
          For the first step, we decided to extract pollen to test its RNA. Our
          aim was to answer three questions:
        </p>

        <ul>
          <li>How much mass of RNA could we extract?</li>
          <li>Which level of purity and integrity could we get?</li>
          <li>How much pollen is necessary to make a cDNA?</li>
        </ul>

        <p>
          Answering the questions was very important because we had a low amount
          of pollen, short time to do the experiments and we didn't had
          experience working on plants, so we were prone to initial failures.
        </p>

        <p>
          To avoid contamination by RNAses we used gloves all the time while
          manipulating the samples, and also used a solution called RNaseZap™
          RNase Decontamination Solution (Invitrogen).
          <b
            >An important point to note is to take great care while grinding the
            pollen with the mortar due to its small size, which renders it
            difficult to see and easy to lose. The advice we have for scientists
            that want to research this topic: use the pestle inside the
            microtube for the disruption of the cells in nitrogen liquid instead
            of the mortar, and add the buffer inside the microtube for cell
            homogeneization. It may well be that you end up losing part of the
            mass due to mistakes during the experiment. Always keep the pollen
            and microtube cold on nitrogen liquid, and TAKE CARE not to burn
            yourself!</b
          >
        </p>

        <p>
          In this experiment we used a pollen from control plant (GLK2 u/u) and
          we got around 20 µg of total RNA from each 20 mg of pollen with the
          RNeasy Plant Mini Kit (QIAGEN) protocol. We eluted the total RNA from
          a silica column with 30 µL of diethyl pyrocarbonate (DEPC) treated
          water. The ration 260/280 nm and 260/230 nm, for identification of
          protein and co-solvents or phenolic compounds, respectively, have
          shown us the good quality, close to 2.0 value (Table 1). After that,
          we have extracted the DNA from leaf as control, according to DNeasy
          Plant Mini Kit (QIAGEN) protocol.
        </p>
        <table class="has-text-centered">
          <tbody>
            <tr>
              <th>Samples</th>
              <th>concentration(ng/µL)</th>
              <th>A <small>260/230</small></th>
              <th>A <small>260/280</small></th>
              <th>
                total mass of tissues(mg of polen or leaf)
              </th>
              <th>
                total mass of acid nucleics extracted(µg)
              </th>
            </tr>
            <tr>
              <td><strong>DNA(Leaf)</strong></td>
              <td>61.6</td>
              <td>1.8</td>
              <td>2.1</td>
              <td>25.0</td>
              <td>1.5</td>
            </tr>
            <tr>
              <td><strong>RNA(Pollen)</strong></td>
              <td>394.9</td>
              <td>2.2</td>
              <td>2.2</td>
              <td>20.0</td>
              <td>20.0</td>
            </tr>
          </tbody>
        </table>

        <small
          >Table 1. Concentration and quality of RNA and DNA extracted from
          Micro-tom control.</small
        >

        <p>
          We removed DNA residues of RNA through TURBO™ DNase (Invitrogen) and
          made an agarose gel 1% (w/v) on 0.5x Tris-Borate-EDTA pH 8.3 (TBE) to
          verify the integrity of 28S, 18S and 5.8S from ribossomal RNA as well
          as to check if it had any DNA contaminants. The results demonstrated
          pure RNA, free of DNA, and not degraded too (Figure 4).
        </p>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/c/cc/T--USP-Brazil--IGEM-USP-Notebook-Genomic.png"
            alt=""
          />
        </figure>

        <h2>
          August 11th 2021 - Transformants plants samples (Members: Marcos,
          Bruno and Beatriz)
        </h2>

        <p>
          Transformant plants were moved to a green house, located in the
          Departamento de Botânica - IB - USP (23°33'59.7"S 46°43'49.9"W)
          (Botany Department) (Figure 5). The green house was acclimatized for
          natural day light and controlled temperature of 30°C.
        </p>
        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/a/af/T--USP-Brazil--IGEM-USP-Notebook-greenhouse.png/800px-T--USP-Brazil--IGEM-USP-Notebook-greenhouse.png"
            alt=""
          />
        </figure>

        <h2>
          August 13th 2021 - Collection of leafs and pollen samples from
          transformants (Members: Luiz)
        </h2>

        <p>
          Fresh leafs and pollen were collected from all transformants Micro-tom
          that looked healthy. Only plant number 2 presented enough pollen mass
          for the experiments. Hence we chose specifically to test the qRT-PCR.
          Experiments for GUS assay needed fresh samples at a maximum of one day
          store after pickup. As most of the plants didn't have flowers
          developed enough for pollen production, we decided to take the pollen
          of mature flowers on September.
        </p>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/b/b6/T--USP-Brazil--IGEM-USP-Notebook-lab.png/583px-T--USP-Brazil--IGEM-USP-Notebook-lab.png"
            alt=""
          />
        </figure>
        <h2>
          August 14th 2021 - Detection of minimum RNA for cDNA synthesis and
          verification of genomic DNA contamination (Members: Caio K., Erick,
          Eric, João and Pedro A.)
        </h2>

        <p>
          With the first and second question presented above being answered, we
          now needed to know the minimum amount of RNA mass we would need for
          cDNA synthesis. Once again, we used the RNA from the control plant and
          diluted it by 1000 ng, 500 ng, 200 ng, 100 ng and 50 ng for each
          solution of 10 µL of transcriptase reaction. We used the SuperScript
          II (Invitrogen), in accordance with their protocol. For each
          synthesis, we did a PCR amplification of Expressed sequence, a
          keephousing gene of tomato [2] donated to us by Prof. Dr. Maria
          Magdalena Rossi (GMP, IB-USP). The primers were designed to amplify a
          greater sequence when the template were genomic DNA and a smaller
          sequence when the template is from RNA (cDNA).
        </p>

        <p>
          The length difference in each amplicon was due to the presence of
          intron regions. It became a useful way of identifying if our RNA
          samples were contamined from genomic DNA or not. We used the Platinum™
          Taq DNA Polymerase (Invitrogen) protocol with 50 ng of DNA genomic as
          template and 2.5 µL from cDNA synthesis reaction. All reactions were
          made at 25 µL final volume. The conditions of the thermocycler were
          set up to 35 cycles, with primers anealling at 60°C and polymerase
          extension for 30 seconds. The agarose gel was made at 2%
          (weight/volume) concentration with Tris-Acetate-EDTA. The
          electrophoresis ran for 40 min at 90V.
        </p>

        <p>
          Our results show that it is possible to use masses as small as 50 ng
          of total RNA to synthesize a detectable cDNA fragment. Beyond this, we
          identified that our extraction and purification of RNA pollen was also
          good for qRT-PCR experiments because our samples didn't had any
          genomic DNA contamination after the degradation with DNAse (Figure 7).
        </p>
        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/9/9d/T--USP-Brazil--IGEM-USP-Notebook-Amplification.png/800px-T--USP-Brazil--IGEM-USP-Notebook-Amplification.png"
            alt=""
          />
        </figure>

        <p>
          For experiments to prove the functionally of our circuit, we designed
          primers with the support of Beacon Designer™ Free Edition
          <a href="http://free.premierbiosoft.com"
            >(http://free.premierbiosoft.com)</a
          >
          and selected a sequence to amplify a junction of LAT52, CYP6G1 and GUS
          in a single amplicon, aiming to identify all the integration of our
          circuit and the internal regions of CYP6G1 (CYP1 and CYP2) and GUS
          (Table 2).
        </p>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/8/81/T--USP-Brazil--IGEM-USP-Notebook-Table2.png"
            alt=""
          />
        </figure>
        <small>
          Table 2. Primers designed to prove the presence of our circuit
          LAT52_CYP6G1_GUS and for quantification of transcripts on RT-qPCR
          experiments.
        </small>

        <h2>
          Table 2. Primers designed to prove the presence of our circuit
          LAT52_CYP6G1_GUS and for quantification of transcripts on RT-qPCR
          experiments.
        </h2>

        <p>
          After finding the optimal procedures for RNA extraction, removal of
          DNA residues and the knowledge of minimum RNA quantity necessary to
          synthesize cDNA from pollen, we started the genomic DNA extraction
          from all transformant plants to find positive transformants for the
          presence of the circuit LAT52-CYP6G1-GUS. As we didn't have extraction
          kits to use on all plants, we extracted the DNA with the protocol
          described by Vennapusa (2021) [3] adapted by students from Laboratory
          of Bioluminescent Fungi - Institute of Chemistry - USP, Brazil. The
          adaptation consisted of breaking the plant cell walls with 1 mL of RNA
          Extraction Buffer at room temperature with support of the SpeedMill
          PLUS Homogenization System (Analytik Jena). Five cycles of 1 minute of
          agitation and 1 minute of rest were made at room temperature. We
          changed the acid phenol saturated solution (ph 4.3) to basic phenol
          solution (pH >7.4) to isolate DNA only. We added the steps for
          precipitation of total RNA using sodium acetate solution 3 M pH 5.2 at
          0.1x of lysate total volume, following the addition of 3x of total
          volume with pure ethanol. The solution was inverted 20 times, and kept
          on ice for 30 min. The RNA was concentrated with centrifugation at
          maximum velocity (>21000xg) at 4°C for 20 min. The aqueous solution
          was discarded and the visible (and invisible) RNA pellets were washed
          twice with 300 µL of ethanol solution 70% (v/v). The white gelatinous
          pellet (our invisible) was dried for 10 minutes at air room
          temperature and eluted with 20 µL of DEPC treated water preheated at
          65°C.
        </p>

        <b
          >Observation: Sometimes, the pellet will not be visible, but DO NOT
          WORRY! Continue the experiment and try to thoroughly elute the walls
          of the microtube with preheated DEPC water treated at 65°C.</b
        >

        <p>
          The DNA was measured and all samples have shown a high amount of mass
          per microlitre with good quality. We tested our plants for detection
          of the gene "Expressed" for validation of the DNA integrity. We made a
          PCR with Platinum™ Taq DNA Polymerase (Invitrogen), according the
          protocol and with 100 ng of DNA for each sample. Our results indicated
          that the extraction of all samples were successful because each PCR
          had shown the expected amplicon from Expressed (Figure 8).
        </p>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/thumb/b/b7/T--USP-Brazil--IGEM-USP-Notebook-Expressed.png/800px-T--USP-Brazil--IGEM-USP-Notebook-Expressed.png"
            alt=""
          />
        </figure>

        <p>
          The agarose gel was made at 1% (weight/volume) concentration with
          Tris-Acetate-EDTA. The electrophoresis ran for 28 min at 130V.
        </p>

        <h2>
          September 1st 2021 - Identification of positives plants for circuit
          LAT52-CYP6G1-GUS (Members: Eric).
        </h2>

        <b>Reagents:</b>

        <ol>
          <li>GoTaq® Hot Start Green Master Mix, 2X (M5122)</li>

          <li>DMSO</li>

          <li>TAE Buffer 1X</li>

          <li>Electrophoresis-grade agarose</li>

          <li>SYBR Safe DNA Gel Stain (S33102)</li>

          <li>1Kb Ladder (M1181)</li>
        </ol>

        <p>
          After obtaining the genomic DNA with the extraction performed by the
          LiCl-SDS method of 11 transgenic lines we started the genomic PCR. The
          wild plant served as a template for the negative control, and plasmid
          extraction of the binary vector E260p9o35s-LAT52-CYP6G1-oGUSi
          previously stored in E. coli DH10B by electro-transformation served as
          positive amplification control. The experiment was performed using
          construct-specific primers in which the forward oligo annealing
          anneals in the middle of the LAT52 promoter sequence (Lat52Cyp-Gus_Fw:
          5'-accgagtcaattgctacaatcac-'3), and reverse oligo annealing anneal at
          the beginning of the GUS reporter gene (Lat52Cyp-Gus_Rv:
          5'-tttgataccagacatttccagcg-'3), giving the total amplicon of 2149 bp.
        </p>

        <p>
          We used 100 ng of each sample to amplify the sequence LAT52-CYP6G1-GUS
          to search a positive transformant that have the complete transference
          sequence from bacteria infection. To do it we used the primers CYP.
          During the experiment, we lost the sample of plant 5 and 16.
        </p>

        <p>Procedure:</p>

        <ol>
          <li>
            A master mix was made on ice for a total of 13 reactions of 15 uL
            each. Values are shown in the following Table 3:
          </li>
          <table class="content" border="1">
            <tr>
              <td>Reagents</td>
              <td>Volume for 15 uL of reaction</td>
              <td>Final volume of Master mix (uL)</td>
            </tr>
            <tr>
              <td>GoTaq® Hot Start Green Master Mix, 2X</td>
              <td>6.5</td>
              <td>84.5</td>
            </tr>
            <tr>
              <td>Primer LATCYPGUS_F (10 uM)</td>
              <td>0.75</td>
              <td>9.75</td>
            </tr>
            <tr>
              <td>Primer LATCYPGUS_R (10 uM)</td>
              <td>0.75</td>
              <td>9.75</td>
            </tr>
            <tr>
              <td>gDNA</td>
              <td>1.5</td>
              <td>19.5</td>
            </tr>
            <tr>
              <td>DMSO</td>
              <td>0.75</td>
              <td>9.75</td>
            </tr>
            <tr>
              <td>Nuclease-Free water</td>
              <td>4.75</td>
              <td>61.75</td>
            </tr>
            <tr>
              <td><b>TOTAL (ul)</b></td>
              <td>15</td>
              <td>195</td>
            </tr>
          </table>

          <small>Table 3: PCR Master mix</small>
          <li>
            Once the master mix was assembled (without the addition of DNA),
            13.5 uL of the master mix was distributed between 13 PCR tubes.
          </li>
          <li>
            After the master mix distribution, 1.5 uL of gDNA from each sample
            of the 11 transgenic lines were added to each tube; 1.5 uL of gDNA
            from the wild plant (negative control) and 1.5 uL of the extracted
            plasmid E260p9o35s-LAT52-CYP6G1 -oGUSi (positive control).
          </li>

          <table border="1">
            <tr>
              <td>Initial denaturation</td>
              <td>Touchdown phase</td>
              <td>Enrichment phase</td>
              <td>Hold</td>
            </tr>
            <tr>
              <td>94°C - 30 sec</td>
              <td>Initial denaturation: 94°C - 20 sec</td>
              <td>Initial denaturation: 94°C - 20 sec</td>
              <td>94°C - ∞</td>
            </tr>
            <tr>
              <td></td>
              <td>Annealing: 62 °C (–1 °C per cycle) - 30 sec</td>
              <td>Annealing: 52 °C - 30 sec</td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td>Extension: 68 °C - 2:15 mins</td>
              <td>Extension: 68 °C - 2:15 mins</td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td>10 cycles</td>
              <td>27 cycles</td>
              <td></td>
            </tr>
          </table>

          <small>Table 4: Touchdown PCR setting:</small>

          <li>
            Once the PCR was completed in the thermocycler, gel electrophoresis
            was performed on the samples to visualize the corresponding
            amplifications of the positive transgenic lines.
          </li>
          <li>
            The 1% agarose concentration was used for 150 mL of the 1X TAE
            buffer, so 1.5 g of agarose was weighed and solubilized in 150 ml of
            the 1X TAE buffer, then heating the solution carefully in the
            microwave until the agar was fully solubilized.
          </li>
          <li>
            After the temperature of the solution reached approximately 50
            degrees, 7.5 µl of SYBR Safe DNA Gel Stain was added and carefully
            homogenized taking care to not form air bubbles.
          </li>
          <li>
            After the stained gel solidified, 5 uL of each sample was placed in
            each well, and 5 uL of the M1181 1Kb ladder (Sinapse). Finally, the
            gel in the electrophoresis cuvette was completed with 1X TAE
            solution.
          </li>
          <li>
            Once the PCR was completed in the thermocycler, gel electrophoresis
            was performed on the samples to visualize the corresponding
            amplifications of the positive transgenic lines.
          </li>
          <li>
            After the run the power source was turned off and the gel was taken
            to the photo-documenter. The result of the race is shown in the
            following Figure 9:
          </li>
          <figure class="has-text-centered">
            <img
              src="https://2021.igem.org/wiki/images/thumb/1/1d/T--USP-Brazil--IGEM-USP-Notebook-Quantification.png/800px-T--USP-Brazil--IGEM-USP-Notebook-Quantification.png"
              alt=""
            />
          </figure>
        </ol>

        <h2>
          September 22nd 2021 - Collection of pollen from Micro-tom
          transformants number 5, 22 and 25 (Members: Marcos and Luiz) and
          experiment of GUS Assay (Members: Luiz).
        </h2>

        <p>
          Mature Micro-tom transformed flowered and the pollen from plants 5, 22
          and 25 were extracted and used on the same day for GUS assay (Figure
          10). The extraction was done the same way as in August 3rd.
        </p>

        <figure class="has-text-centered">
          <img
            style="max-widht:60%; max-height:60%"
            src="https://2021.igem.org/wiki/images/1/1d/T--USP-Brazil--IGEM-USP-Notebook-Transformed-micro-tom.png"
            alt=""
          />
        </figure>

        <p>
          The assay followed <b>Goldbio Biotechnology's protocol</b> [4]. The
          X-Gal (5-bromo-4-chloro-3-indolyl-β-d-galactopyranoside) reagent was
          donated for us by Prof. Dr. Igor Cesarino (LigninLab - IB, USP). X-Gal
          is used to verify the activity of GUS by the production of a
          chromogenic substrate that can be seen with a simple microscope. If it
          shows functional activity, we could prove that the traduction of our
          circuit transcript is working well. Fresh pollen was collected from
          the transgenic plant's flowers using a brushless electric toothbrush
          (Video 1). The flowers were vibrated to release pollen into a 500 μL
          microtube. A Micro-tom control was used as a negative control. The
          leafs from a transgenic plant expressing GUS under CamV35S promoter
          were used as a positive control.
        </p>

        <p>
          Following pollen collection, the flowers were also cut and stored on
          1.5 mL microtubes.
        </p>

        <p>The staining solution was prepared using:</p>

        <ul>
          <li>50mM ferrocyanide 400 μL</li>
          <li>50mM ferricyanide 400 μL</li>
          <li>500mM NaPO4 at pH 7 400 μL</li>
          <li>20 mg/ml X-Gluc (in DMF) 100 μL</li>
          <li>dH2O 2700 μL</li>
        </ul>

        <p>
          40 microliters of the staining solution were pipetted over the freshly
          collected pollen and incubated for 24h at 37°C. A leaf from the
          positive control was submerged in 100 microliters of the staining
          solution. A 10 ml syringe was used to press the solution into the
          plant tissue. The leaf was incubated on a petri dish under the same
          conditions as the pollen.
        </p>

        <p>
          The flowers were distributed on a 96 well plate and covered in 100
          microliters of the straining solution alongside two leaf fragments
          from the positive control. They were incubated in the same conditions
          as the pollen.
        </p>

        <h2>
          September 29th 2021 - RNA extraction from tissues from Micro-tom
          transformant number 2 and control (Members: Caio K.) and results of
          GUS assay (Members: Luiz).
        </h2>

        <p>
          For the first step we tried to extract the RNA of leafs and pollen
          from plant 2 and a micro-tom control. This time we used the kit
          PureLink™ RNA Mini Kit (Invitrogen) and, before, we disrupted the cell
          walls with fast freeze and used mortar and pestle to pulverize it. We
          followed the protocol and eluated the RNA from column using 30 µL of
          DEPC treated water. For leafs, we obtained a higher mass of acid
          nucleics, reaching 24 µg, different from pollen, where we got just 1.5
          µg.
        </p>

        <p>
          After digestion of residual DNA, we made a 0.5x Tris-Borate-EDTA pH
          8.3 (TBE) 1% (m/v) agarose gel for visualization of the integrity of
          200 ng of RNA of each extraction. The gel showed that the RNA of
          pollen had integrity, as obtained on first experiments, and that the
          RNA of leafs didn't had a good integrity (Figure 11).
        </p>

        <figure class="has-text-centered">
          <img
            style="max-width:70%;max-height:70%"
            src="https://2021.igem.org/wiki/images/3/39/T--USP-Brazil--IGEM-USP-Notebook-RNA-integrity.png"
            alt=""
          />
        </figure>
        <p>
          The preview of the validation of transcript of CYP6G1, the simple PCR
          with qRT-PCR primers (Table 2, CYP1), was made using cDNA synthesized
          with RNA pollen of plant 2 and RNA from control (GLK2 u/u). Two
          reactions were planned using different templates to prove that we
          didn't have contamination of genomic PCR. One reaction had the RNA
          treated by DNase and other the synthesis of cDNA from that sample.
          Fortunately, we detected the presence of CYP6G1 amplicon sequence,
          with the expected length (Figure 12).
        </p>

        <figure class="has-text-centered">
          <img
            style="max-width:70%;max-height:70%"
            src="https://2021.igem.org/wiki/images/4/43/T--USP-Brazil--IGEM-USP-Notebook-_Amplification-of-internal.png"
            alt=""
          />
        </figure>

        <p>
          After the incubation period of the GUS assay, a sample of pollen was
          collected from each microtube with a sterile platinum rod and spread
          on a microscope slide. Light microscopy was used to scan the slide for
          blue pollen cells. The flowers and leaves were submerged in ethanol
          70% for up to 24h and screened for blue-dyed tissue under 40x
          magnification.
        </p>

        <figure class="has-text-centered">
          <img
            style="max-width:70%;max-height:70%"
            src="https://2021.igem.org/wiki/images/1/10/T--USP-Brazil--IGEM-USP-Notebook-GUS-staining.png"
            alt=""
          />
        </figure>

        <p>
          Plants 2 and 22 were the only intersection between biomolecular and
          biochemical experiments. Genomic PCR confirmed the presence of the
          construct in both lineages. Even though it was not possible to extract
          fresh pollen from plant number 2, pollen grains attached to its
          ovarium walls were stained during the flower staining experiment.
          Nevertheless, Let.it.bee's expression was later confirmed in plant
          number 2 through qRT-PCR.
        </p>

        <p>
          One might notice that the amount of stained pollen cells is fairly
          small. Additionally, the intensity of the blue hue also varies between
          grains. However odd this may look, those were expected results. The
          reason for that is that all experiments were carried out with T0
          plants (generation number 0 of the transgenic lineages). It is known
          that *Agrobacterium* mediated transformation happens randomly [5] and
          not all cells are transformed equally. Therefore, the plant presents a
          chimeric genotype in which the expression of the Let.it.bee construct
          is expected to vary among different cells and to be absent in the
          majority of them.
        </p>

        <p>
          The flower tissue staining procedure failed as the positive control we
          used for it did not stain. A possible reason for that is the lack of a
          vacuum pump to push x-gluc into the cells. Therefore, it wasn't
          possible to determine whether the LAT52 promoter was leaking to
          adjacent tissues. Nevertheless, that assumption was previously
          confirmed in the literature and later through qRT-PCR of leaf tissue.
        </p>

        <h2>
          October 1st 2021 - Re-extraction of RNA from pollen control and leaf
          plant 2 (Members: Caio K.)
        </h2>

        <p>
          With these two problems (bad quality of RNA leaves and contamination
          of RNA control pollen samples) we tried to fix the first issue by
          changing the method of RNA extraction. For control and plant 2 leaves,
          we used the optimized protocol of TRIzol™ Reagent (Invitrogen) [6]
          and, again, we obtained a higher quantity of RNA and with good quality
          (Figure 14).
        </p>

        <p>
          For the extraction of pollen of control plant, we used the PureLink™
          RNA Mini Kit (Invitrogen). This time we extracted only the tissue as a
          template in the day in order to avoid the contamination of RNA.
        </p>

        <p>
          he agarose gel was made at Tris-Acetate-EDTA pH 8.0 (TAE) 1% (m/v) and
          showed the integrity of RNA of the leafs, even after the treatment of
          DNAse. It showed us that the extraction of RNA from leaves is
          <b
            >better with TRIzol™ Reagent (Invitrogen) than PureLink™ RNA Mini
            Kit (Invitrogen)</b
          >. But the RNA from plant 2 was strange, without a 28S band (Figure
          14).
        </p>

        <figure class="has-text-centered">
          <img
            style="max-width:70%;max-height:70%"
            src="https://2021.igem.org/wiki/images/1/17/T--USP-Brazil--IGEM-USP--Notebook-Total-RNA-extracted.png"
            alt=""
          />
        </figure>

        <h2>
          October 1st 2021 - Re-extraction of RNA from leafs plant 2 (Members:
          Caio K.)
        </h2>

        <p>
          We have extracted one more time the RNA from leafs of plant 2 using
          TRIzol™ Reagent (Invitrogen) and, finally, we could get RNA with high
          quality and integrity (Figure 15). The advice taken from this
          experiments is: do not worry if your RNA does not precipitates as a
          pellet and the microtube appearing to have nothing. The RNA may be
          stuck on the microtube walls after centrifugation so you can continue
          washing it with the ethanol solution until it gets unstuck. As another
          last resource, you may try to elute the invisible RNA with water
          (preheated at 65°C) on the edge of microtube. Remember that RNA is
          much smaller and we cannot see it sometimes!
        </p>

        <figure class="has-text-centered">
          <img
            style="max-width:70%;max-height:70%"
            src="https://2021.igem.org/wiki/images/a/ae/T--USP-Brazil--IGEM-USP-Notebook-Total-RNA-extracted.png"
            alt=""
          />
        </figure>
        <p>
          In all the times we got the RNA integrity with good quality, we used
          600 ng to synthesize the cDNA on a final volume of 30 µL. This time we
          used the Super Script IV following the protocol. The cDNA reaction was
          set up at 55°C and after inhibition, we stored it at -20°C.
        </p>

        <h2>
          October 6th 2021 - Validation of the best concentration of qRT-PCR
          primers (Members: Caio K.)
        </h2>

        <p>
          We have measured the concentration of cDNA synthesis on
          NanoPhotometer® NP80 and the primer efficience was determined using
          dilutions of cDNA from 200 ng, 100 ng, 50 ng, 25 ng and 12.5 ng for
          CYP2, GUS and expressed primers at duplicates (Figure 16).
        </p>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/5/5f/T--USP-Brazil--IGEM-USP-Notebook-cDNA-standard.png"
            alt=""
          />
        </figure>

        <p>
          The melting curve has shown us that we didn't have an inespecific
          amplification (Figure 17) and contamination by genomic DNA. We know
          that because the gene expressed had only one melting curve. If it had
          shown two curves, one for 300pb sequence and the second 200pb, it
          would mean contamination. We already proved two lengths of feasibility
          Expressed amplicons when we amplified from DNA and RNA (cDNA) (Figure
          17).
        </p>

        <figure class="has-text-centered">
          <img
            style="max-width:80%;max-height:80%"
            src="https://2021.igem.org/wiki/images/7/78/T--USP-Brazil--IGEM-USP-Notebook-Melting-curve.png"
            alt=""
          />
        </figure>

        <p>
          The results shows that the best concentration for RT-qPCR assay was 50
          ng of cDNA. With the standard curve, we calculated the efficiency of
          primers that showed as good to continue with the experiment (Table 5).
        </p>
        <figure class="has-text-centered">
          <img
            style="max-width:70%; max-height:70%"
            src="https://2021.igem.org/wiki/images/a/a1/T--USP-Brazil--IGEM-USP--Notebook-Efficiency-primers.png"
            alt=""
          />
        </figure>

        <h2>October 7th 2021 - RT-qPCR assay (Members: Caio K.)</h2>

        <p>
          After obtaining good quality samples of cDNA from RNA tissues (pollen
          and leaf) for control and t2 plants, with the knowledge of the
          validation of specific primers and the best concentration for
          experiments, we done the RT-qPCR assay in duplicate, with 50 ng of
          cDNA, a negative control and the Expressed as reference and
          keephousing primers. Our results showed that only pollen of T2 had
          detectable active transcripts, with eight cycles earlier than
          Expressed (Table 6). The Ct represents the minimum threshold that the
          fluorescence must have to be detectable to indicate amplification
          without being a noises of the machine detector. Pollen, leaf controls
          and Leaf T2 showed a long amplified or undetermined values of Ct,
          which indicates the absence of transcripts in these tissues.
        </p>

        <figure class="has-text-centered">
          <img
            src="https://2021.igem.org/wiki/images/b/b5/T--USP-Brazil--IGEM-USP-Notebook-Table6.png"
            alt=""
          />
        </figure>
        <small>
          >Table 6. Average of Ct values of duplicates experiments from pollen
          and leaf samples from control and T2 plant (transformed plant number
          2).</small
        >
        <h2>Reference:</h2>
        <div class="references">
          <ol>
            <li>
              Nguyen CV, Vrebalov JT, Gapper NE, et al. Tomato GOLDEN2-LIKE
              transcription factors reveal molecular gradients that function
              during fruit development and ripening. Plant Cell.
              2014;26(2):585-601. doi:10.1105/tpc.113.118794
            </li>

            <li>
              Expósito-Rodríguez M, Borges AA, Borges-Pérez A, Pérez JA.
              Selection of internal control genes for quantitative real-time
              RT-PCR studies during tomato development process. BMC Plant Biol.
              2008 Dec 22;8:131. doi: 10.1186/1471-2229-8-131. PMID: 19102748;
              PMCID: PMC2629474.
            </li>

            <li>
              Vennapusa AR, Somayanda IM, Doherty CJ, Jagadish SVK. A universal
              method for high-quality RNA extraction from plant tissues rich in
              starch, proteins and fiber. Sci Rep. 2020 Oct 9;10(1):16887. doi:
              10.1038/s41598-020-73958-5. PMID: 33037299; PMCID: PMC7547072.
            </li>

            <li>
              Gold Biotechnology. (2016). Histochemical Staining of GUS Reporter
              Activity. Retrieved from
              https://www.goldbio.com/documents/1052/Histochemical Staining of
              GUS Reporter Activity.pdf.
            </li>

            <li>
              Gelvin, S. B. (2017). Integration of Agrobacterium T-DNA into the
              Plant Genome. Annual Review of Genetics, 51(1), 195–217.
              doi:10.1146/annurev-genet-120215-035320
            </li>

            <li>
              Thermo Fisher Scientific. (2020). TRIzol™ Reagent User Guide.
              Retrieved from
              [https://assets.thermofisher.com/TFS-Assets/LSG/manuals/trizol_reagent.pdf](https://assets.thermofisher.com/TFS-Assets/LSG/manuals/trizol_reagent.pdf).
            </li>
          </ol>
        </div>
      </div>

      <div class="column is-one-fifth"></div>
    </section>

    <Footer />
  </div>
</template>

<script>
import Nav from "@/components/Nav.vue";
import Footer from "@/components/Footer.vue";
import Backtotop from "@/components/BacktoTop.vue";
export default {
  name: "Safety",
  components: {
    Nav,
    Footer,
    Backtotop,
  },
};
</script>

<style scoped>
table {
  border: 4pt solid #ffba17;
  color: #040404;
  font-size: 18px;
  font-family: "Poppins", sans-serif;
  font-weight: 400;
}
li {
  color: #040404;
  font-size: 18px;
  font-family: "Poppins", sans-serif;
  font-weight: 400;
}
table b {
  color: #040404;
}
th {
  font-size: 20px;
  color: #040404;
  text-align: center;
}
</style>
